Generate Multiple interfaces based on first Tag
christianhelle/refitter pull request #95
Opened 2023-08-05 07:41 UTC by kirides

This PR adds an additional mode for `--multiple-interfaces` called `ByTag` which uses the first Tag of the operation to generate the interface name.

This PR also adds a `BREAKING` change as `--multiple-interfaces` now takes in an enumeration of `Unset`, `ByEndpoint` and `ByTag`.
The source generator `.refitter` file has the same breaking change, as it now takes its value as string like this:
```json
{
  "multipleInterfaces": "ByTag" // or ByEndpoint
}
```

Generated sample:
```cs
namespace GeneratedCode
{
    // No/Empty first Tag 
    public interface IDocumentV1Api
    {
        [Get("/api/greet-unsafe")]
        Task GreetUnsafe([Query] string name);
    }

    // tag "Greeting"
    public interface IGreetingApi
    {
        [Get("/api/greet")]
        Task Greet([Query] string name);
    }

    // tag "OpenApi"
    public interface IOpenApiApi
    {
        [Get("/api/custom-docs")]
        Task<ICollection<Item>> CustomDocs([Query] string name);

        [Get("/api/some-other-thing")]
        Task<ICollection<Item>> SomeOtherThing([Query] string name);
    }

}
```

2023-08-05 19:56 UTC, christianhelle commented
@kirides this is some very good stuff! I don't mind the breaking change since as far as I know, I'm the only one using `--multiple-interfaces` but we should update the source generator README

2023-08-05 20:11 UTC, christianhelle commented
@all-contributors please add @kirides for code

2023-08-05 20:33 UTC, christianhelle requested changes
@kirides The builds are failing because `--multiple-interfaces` is now expecting an extra argument

Can I ask you to update **line 60** in the file **`.github\workflows\template.yml`** to

```yml
${{ inputs.command }} ./openapi.${{ inputs.format }} --namespace "$namespace.MultipleInterfaces" --output "MultipleInterfaces$outputPath" --multiple-interfaces ByEndpoint --no-logging
```

and **line 116-119** in the file **`test\smoke-tests.ps1`** to:

```pwsh
Write-Host "dotnet run --project ../src/Refitter/Refitter.csproj ./openapi.$format --namespace $namespace.MultipleInterfaces --output ./GeneratedCode/MultipleInterfaces$outputPath --multiple-interfaces ByEndpoint --no-logging"
$process = Start-Process "dotnet" `
    -Args "run --project ../src/Refitter/Refitter.csproj ./openapi.$format --namespace $namespace.MultipleInterfaces --output ./GeneratedCode/MultipleInterfaces$outputPath --multiple-interfaces ByEndpoint --no-logging" `
    -NoNewWindow `
    -PassThru
```

2023-08-05 20:36 UTC, christianhelle requested changes
@kirides if its not too much trouble, please update **`src\Refitter.SourceGenerator\README.md`** so the example .refitter file and explanations match the proposed changes

2023-08-06 06:19 UTC, kirides commented
Sure will do those things.
Just gotta get on to a PC :)

2023-08-06 06:56 UTC, christianhelle commented
@kirides thanks! 

Remember to enjoy the weekend first 😄

2023-08-06 10:32 UTC, christianhelle approved these changes

2023-08-06 10:33 UTC, merged